package br.com.chat.profile.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "chat-app-profile")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Profile {

    @JsonView(Views.ViewStatusProfile.class)
    @JsonProperty("id")
    private String id;

    @JsonView(Views.ViewStatusProfile.class)
    private List<Status> statusList;

    @DynamoDBAttribute(attributeName = "statusList")
    public List<Status> getStatusList() {
        if (statusList == null)
            this.statusList = new ArrayList<>();
        return statusList;
    }

    public void setStatusList(List<Status> statusList) {
        this.statusList = statusList;
    }

    @DynamoDBHashKey(attributeName = "profileId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String categoryId) {
        this.id = categoryId;
    }
}
