package br.com.chat.profile.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
@DynamoDBDocument
public class Status {

    @JsonView(Views.ViewStatusProfile.class)
    @JsonProperty("id")
    private String id;

    @JsonProperty("profile_id")
    private String profileId;

    @JsonView(Views.ViewStatusProfile.class)
    @JsonProperty("date")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    @DynamoDBAttribute(attributeName = "date")
    @DynamoDBTypeConvertedTimestamp
    private Date date;

    @JsonView(Views.ViewStatusProfile.class)
    @JsonProperty("text")
    private String text;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @DynamoDBAttribute(attributeName = "text")
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String categoryId) {
        this.id = categoryId;
    }

    @DynamoDBIgnore
    public String getProfileId() {
        return profileId;
    }

    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
}
